# Generated by Django 2.2.5 on 2020-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_bancarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('cuenta_banco', models.IntegerField()),
                ('banco', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_personales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.CharField(max_length=25)),
                ('numero_registro', models.IntegerField()),
                ('vigencia', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=255)),
                ('promedio', models.FloatField()),
                ('cantidad_votos', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar_trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('lugar_trabajo', models.CharField(max_length=255)),
                ('horario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monedero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('fecha_mov', models.FloatField()),
                ('monto', models.IntegerField()),
                ('origen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('puntuacion', models.FloatField()),
                ('comentarios', models.CharField(max_length=255)),
                ('reclamos', models.CharField(max_length=255)),
            ],
        ),
    ]
