# Generated by Django 2.2.5 on 2020-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeLoCuido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('foto', models.CharField(max_length=2083)),
            ],
        ),
    ]
