# Generated by Django 3.0.3 on 2020-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeLoCuido', '0002_woow'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar_trabajo',
            name='latitud',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugar_trabajo',
            name='longitud',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
