# Generated by Django 3.0.3 on 2020-03-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeLoCuido', '0003_auto_20200314_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_personales',
            name='direccion_trabajo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='horario_fin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='horario_inicio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='latitud_trabajo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='longitud_trabajo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos_personales',
            name='nombre_lugar_trabajo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
