# Generated by Django 3.0.3 on 2020-03-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeLoCuido', '0004_auto_20200330_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_personales',
            name='lugares_libres',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
