# Generated by Django 3.0.3 on 2020-03-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeLoCuido', '0005_datos_personales_lugares_libres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lugar_trabajo',
        ),
    ]
