# Generated by Django 3.0.3 on 2020-04-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeLoCuido', '0006_delete_lugar_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_personales',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='vigencia',
            field=models.DateTimeField(),
        ),
    ]
