# Generated by Django 3.0.3 on 2020-04-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeLoCuido', '0007_auto_20200401_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_personales',
            name='cantidad_votos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='direccion_trabajo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='horario_fin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='horario_inicio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='image_url',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='latitud_trabajo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='longitud_trabajo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='lugares_libres',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='nombre_lugar_trabajo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='promedio',
            field=models.FloatField(null=True),
        ),
    ]
